# Autogenerated wrapper script for opam_jll for x86_64-linux-musl
export opam

JLLWrappers.@generate_wrapper_header("opam")
JLLWrappers.@declare_executable_product(opam)
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_executable_product(
        opam,
        "bin/opam",
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
